// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6Br-A4zCDi0dHsxdANfVRqElte_VOa4',
    appId: '1:724990847891:web:7567b46bd6740332559666',
    messagingSenderId: '724990847891',
    projectId: 'ourverses-dev',
    authDomain: 'ourverses-dev.firebaseapp.com',
    storageBucket: 'ourverses-dev.appspot.com',
    measurementId: 'G-LR2CY6K7VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsgS1YhU7WE1oeBg9LqVDABwCsvt9BcM4',
    appId: '1:724990847891:android:1f5f9dbf8f152ee1559666',
    messagingSenderId: '724990847891',
    projectId: 'ourverses-dev',
    storageBucket: 'ourverses-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJHCGMj1Gm2SGGCYgKjz4OX9q_gmeTcs',
    appId: '1:724990847891:ios:bed643b8d74fa29c559666',
    messagingSenderId: '724990847891',
    projectId: 'ourverses-dev',
    storageBucket: 'ourverses-dev.appspot.com',
    iosClientId: '724990847891-jc8044e88c06jp57u84h29gnldscgo6p.apps.googleusercontent.com',
    iosBundleId: 'app.anirac.ourverses.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJHCGMj1Gm2SGGCYgKjz4OX9q_gmeTcs',
    appId: '1:724990847891:ios:bed643b8d74fa29c559666',
    messagingSenderId: '724990847891',
    projectId: 'ourverses-dev',
    storageBucket: 'ourverses-dev.appspot.com',
    iosClientId: '724990847891-jc8044e88c06jp57u84h29gnldscgo6p.apps.googleusercontent.com',
    iosBundleId: 'app.anirac.ourverses.dev',
  );
}
