name: ourverses

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: "./coverage/lcov.info"
          min_coverage: 95
          #exclude: "**/*_observer.dart **/change.dart"
        # Note: Above is how you do exclusions and min percentages
        # they advise to keep 100% code coverage for new projects
        # perhaps that's possible for awhile
        # https://verygood.ventures/blog/very-good-coverage
